name: evaluate_model_cml
on:
  pull_request:
    branches: [ dev ]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Evaluate model
        run: |
          pip install -r requirements.txt
          python src/models/model1/test.py
      - name: Write report
        env:
          # this authenticates that the right permissions are in place
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # send all information to report.md that will be reported to us when the workflow finish
          cat evaluation_report.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
